### ISSUE TITLE
What are our Terms of Service?

### ISSUE THREAD

**Issue by viveret** [pink-umbrella/pink-umbrella#11]
What are our terms of service? Should it be up to the server instance?

**Comment by sainteos** [comment]
Hmmm, I'm not sure. I'm not too familiar with that, is that different than a software license?

**Comment by viveret** [comment]
It is essentially what you are and are not allowed to do with the software. The system should ultimately handle abuse, but the terms of service should tell users what expectations are for online behavior or use of this software before they are allowed to sign up. If they violate the terms of service, their access to the software can be limited or removed. This wouldn't stop them from trying to bypass the ToS or rules, but for the average user it helps to know what can get you in trouble so you can avoid it.

**Comment by viveret** [comment]
The software license is for whoever is running the software, or using the software, but usually includes legal information on rights of usage, distribution, renaming, modifying, selling, or other things like that. End users don't really intend to do any of that (other than use it) so I feel it should be a separate document.

**Comment by sainteos** [comment]
Ohhh gotcha, that makes sense. Should we also include a software license for people to stand up and modify their own instances? I personally try to do GPLv3 as much as I can

**Comment by viveret** [comment]
GPLv3 will probably work, I was going to make it public domain otherwise

**Comment by sainteos** [comment]
I generated a TOS, to start with:
# Website Terms and Conditions of Use

## 1. Terms

By accessing this Website, accessible from pink-umbrella.ninja, you are agreeing to be bound by these Website Terms and Conditions of Use and agree that you are responsible for the agreement with any applicable local laws. If you disagree with any of these terms, you are prohibited from accessing this site. The materials contained in this Website are protected by copyright and trade mark law. These Terms of Service has been created with the help of the [Terms of Service Generator](https://www.termsofservicegenerator.net) and the [Terms & Conditions Example](https://www.termsconditionsexample.com)".

## 2. Use License

Permission is granted to temporarily download one copy of the materials on Pink Umbrella's Website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:

- modify or copy the materials;
- use the materials for any commercial purpose or for any public display;
- attempt to reverse engineer any software contained on Pink Umbrella's Website;
- remove any copyright or other proprietary notations from the materials; or
- transferring the materials to another person or "mirror" the materials on any other server.

This will let Pink Umbrella to terminate upon violations of any of these restrictions. Upon termination, your viewing right will also be terminated and you should destroy any downloaded materials in your possession whether it is printed or electronic format.

## 3. Disclaimer

All the materials on Pink Umbrella’s Website are provided "as is". Pink Umbrella makes no warranties, may it be expressed or implied, therefore negates all other warranties. Furthermore, Pink Umbrella does not make any representations concerning the accuracy or reliability of the use of the materials on its Website or otherwise relating to such materials or any sites linked to this Website.

## 4. Limitations

Pink Umbrella or its suppliers will not be hold accountable for any damages that will arise with the use or inability to use the materials on Pink Umbrella’s Website, even if Pink Umbrella or an authorize representative of this Website has been notified, orally or written, of the possibility of such damage. Some jurisdiction does not allow limitations on implied warranties or limitations of liability for incidental damages, these limitations may not apply to you.

## 5. Revisions and Errata

The materials appearing on Pink Umbrella’s Website may include technical, typographical, or photographic errors. Pink Umbrella will not promise that any of the materials in this Website are accurate, complete, or current. Pink Umbrella may change the materials contained on its Website at any time without notice. Pink Umbrella does not make any commitment to update the materials.

## 6. Links

Pink Umbrella has not reviewed all of the sites linked to its Website and is not responsible for the contents of any such linked site. The presence of any link does not imply endorsement by Pink Umbrella of the site. The use of any linked website is at the user’s own risk.

## 7. Site Terms of Use Modifications

Pink Umbrella may revise these Terms of Use for its Website at any time without prior notice. By using this Website, you are agreeing to be bound by the current version of these Terms and Conditions of Use.

## 8. Your Privacy

Please read our [Privacy Policy](https://www.privacypolicygenerator.info/).

## 9. Governing Law

Any claim related to Pink Umbrella's Website shall be governed by the laws of us without regards to its conflict of law provisions.

**Comment by viveret** [comment]
We can make it a Markdown file so that the site can read it and display it at /Terms or /ToS and also on GitHub. 

Also, my only notes are we could reword the governing law section, and use license would be the GPL license. We want to allow the things this ToS does not allow for redistribution and modification.

**Comment by viveret** [comment]
We will also have to reword it for the P2P decentralized model so that different instances can have their own ToS
